--- # develop
server:
  port: 9002

spring:
  profiles:
    active: develop

MONGO_URI: mongodb://127.0.0.1
MONGO_PORT: 27017
MONGO_DBNAME: mongo-develop


--- # staging
server:
  port: 9003

spring:
  profiles:
    active: staging

MONGO_URI: mongodb://127.0.0.1
MONGO_PORT: 27017
MONGO_DBNAME: mongo-staging


--- # cloud
server:
  port: 9004

spring:
  profiles:
    active: cloud

MONGO_URI: mongodb://127.0.0.1
MONGO_PORT: 27017
MONGO_DBNAME: mongo-cloud
